version: '3.4'

services:
  votingdata:
    image: ${DOCKER_REGISTRY-}votingdata
    build:
      context: .
      dockerfile: VotingData/Dockerfile

  votingweb:
    image: ${DOCKER_REGISTRY-}votingweb
    build:
      context: .
      dockerfile: VotingWeb/Dockerfile

