version: '3.4'

services:
  votingdata:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - RepositoryService__CosmosDb__EndpointUri=https://aksvoting.documents.azure.com:443/
      - RepositoryService__CosmosDb__PrimaryKey=KHkXHmVIAbi7OSkNtZZ3AfiXZEckXmsr7qBEHgI8nEGiV7UzsWvPDrIDBIKslSAJ4l6bsQR034qh9rRyin7ZgA==
      - RepositoryService__CosmosDb__DatabaseName=Election
      - RepositoryService__CosmosDb__CollectionName=Votes
      - NotificationService__ServiceBus__ConnectionString=Endpoint=sb://paolos.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=6qE8PZo0/osXwb1TWpreSXARTXLeFG8gd9vPbKtlOV4=
      - NotificationService__ServiceBus__QueueName=votes
      - ApplicationInsights__InstrumentationKey=81066cbf-d24c-4e1a-9c93-3835c5b3bfd2
    ports:
      - "80"

  votingweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - VotingDataEndpoint=votingdata
      - ApplicationInsights__InstrumentationKey=81066cbf-d24c-4e1a-9c93-3835c5b3bfd2
    ports:
      - "80"

