apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-configmap
  namespace: default
data:
  aspNetCoreEnvironment: Docker
  queueName: votes
  votingDataEndpoint: voting-data
---
apiVersion: v1
kind: Secret
metadata:
  name: voting-secret
type: Opaque
data:
  cosmosDbEndpointUri: aHR0cHM6Ly9ha3N2b3RpbmcuZG9jdW1lbnRzLmF6dXJlLmNvbTo0NDMv
  cosmosDBPrimaryKey: S0hrWEhtVklBYmk3T1NrTnRaWjNBZmlYWkVja1htc3I3cUJFSGdJOG5FR2lWN1V6c1d2UERySURCSUtzbFNBSjRsNmJzUVIwMzRxaDlyUnlpbjdaZ0E9PQ==
  cosmosDbDatabaseName: RWxlY3Rpb24=
  cosmosDbCollectionName: Vm90ZXM=
  serviceBusConnectionString: RW5kcG9pbnQ9c2I6Ly9wYW9sb3Muc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT02cUU4UFpvMC9vc1h3YjFUV3ByZVNYQVJUWExlRkc4Z2Q5dlBiS3RsT1Y0PQ==
  applicationInsightsInstrumentationKey: ODEwNjZjYmYtZDI0Yy00ZTFhLTljOTMtMzgzNWM1YjNiZmQy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voting-data
  labels:
    app: voting-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-data
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: voting-data
    spec:
      containers:
      - name: voting-data
        image: paolosalvatori.azurecr.io/votingdata:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: voting-configmap
              key: aspNetCoreEnvironment
        - name: RepositoryService__CosmosDb__EndpointUri
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: cosmosDbEndpointUri
        - name: RepositoryService__CosmosDb__PrimaryKey
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: cosmosDBPrimaryKey
        - name: RepositoryService__CosmosDb__DatabaseName
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: cosmosDbDatabaseName
        - name: RepositoryService__CosmosDb__CollectionName
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: cosmosDbCollectionName
        - name: NotificationService__ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: serviceBusConnectionString
        - name: NotificationService__ServiceBus__QueueName
          valueFrom:
            configMapKeyRef:
              name: voting-configmap
              key: queueName
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: applicationInsightsInstrumentationKey
---
apiVersion: v1
kind: Service
metadata:
  name: voting-data
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: voting-data
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voting-web
  labels:
    app: voting-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: voting-web
    spec:
      containers:
      - name: voting-web
        image: paolosalvatori.azurecr.io/votingweb:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: voting-configmap
              key: aspNetCoreEnvironment
        - name: VotingDataEndpoint
          valueFrom:
            configMapKeyRef:
              name: voting-configmap
              key: votingDataEndpoint
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
            secretKeyRef:
                name: voting-secret
                key: applicationInsightsInstrumentationKey
---
apiVersion: v1
kind: Service
metadata:
  name: voting-web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: voting-web